# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c04ca14cf9378c86ba8ae9a9cf00d40e63fcb2755728541448c19a4e7e0d0b2697c44eed57b699871eda36955f5dbb42413d21049968c1e44b781dcf0375d53

test:
  secret_key_base: a0fd13c4c1fcd3a95e713f25d818b4f55857971de8b8c08e7d46a3a9f8a394ca9d81657f9408624b0e149f09cd19a1a98864d0ac43aa0339b57844fc4c74f0b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
